// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chat_service.proto
#ifndef GRPC_chat_5fservice_2eproto__INCLUDED
#define GRPC_chat_5fservice_2eproto__INCLUDED

#include "chat_service.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace chat {

class ChatService final {
 public:
  static constexpr char const* service_full_name() {
    return "chat.ChatService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status TextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq& request, ::chat::TextChatMsgRsp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::TextChatMsgRsp>> AsyncTextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::TextChatMsgRsp>>(AsyncTextChatMsgRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::TextChatMsgRsp>> PrepareAsyncTextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::TextChatMsgRsp>>(PrepareAsyncTextChatMsgRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void TextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq* request, ::chat::TextChatMsgRsp* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void TextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq* request, ::chat::TextChatMsgRsp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void TextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq* request, ::chat::TextChatMsgRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::TextChatMsgRsp>* AsyncTextChatMsgRaw(::grpc::ClientContext* context, const ::chat::TextChatMsgReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::TextChatMsgRsp>* PrepareAsyncTextChatMsgRaw(::grpc::ClientContext* context, const ::chat::TextChatMsgReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status TextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq& request, ::chat::TextChatMsgRsp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::TextChatMsgRsp>> AsyncTextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::TextChatMsgRsp>>(AsyncTextChatMsgRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::TextChatMsgRsp>> PrepareAsyncTextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::TextChatMsgRsp>>(PrepareAsyncTextChatMsgRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void TextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq* request, ::chat::TextChatMsgRsp* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void TextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq* request, ::chat::TextChatMsgRsp* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void TextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq* request, ::chat::TextChatMsgRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::chat::TextChatMsgRsp>* AsyncTextChatMsgRaw(::grpc::ClientContext* context, const ::chat::TextChatMsgReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::TextChatMsgRsp>* PrepareAsyncTextChatMsgRaw(::grpc::ClientContext* context, const ::chat::TextChatMsgReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_TextChatMsg_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status TextChatMsg(::grpc::ServerContext* context, const ::chat::TextChatMsgReq* request, ::chat::TextChatMsgRsp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_TextChatMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TextChatMsg() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_TextChatMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TextChatMsg(::grpc::ServerContext* /*context*/, const ::chat::TextChatMsgReq* /*request*/, ::chat::TextChatMsgRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTextChatMsg(::grpc::ServerContext* context, ::chat::TextChatMsgReq* request, ::grpc::ServerAsyncResponseWriter< ::chat::TextChatMsgRsp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_TextChatMsg<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_TextChatMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_TextChatMsg() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::chat::TextChatMsgReq, ::chat::TextChatMsgRsp>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::chat::TextChatMsgReq* request, ::chat::TextChatMsgRsp* response) { return this->TextChatMsg(context, request, response); }));}
    void SetMessageAllocatorFor_TextChatMsg(
        ::grpc::experimental::MessageAllocator< ::chat::TextChatMsgReq, ::chat::TextChatMsgRsp>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat::TextChatMsgReq, ::chat::TextChatMsgRsp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_TextChatMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TextChatMsg(::grpc::ServerContext* /*context*/, const ::chat::TextChatMsgReq* /*request*/, ::chat::TextChatMsgRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* TextChatMsg(
      ::grpc::CallbackServerContext* /*context*/, const ::chat::TextChatMsgReq* /*request*/, ::chat::TextChatMsgRsp* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* TextChatMsg(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::chat::TextChatMsgReq* /*request*/, ::chat::TextChatMsgRsp* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_TextChatMsg<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_TextChatMsg<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_TextChatMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TextChatMsg() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_TextChatMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TextChatMsg(::grpc::ServerContext* /*context*/, const ::chat::TextChatMsgReq* /*request*/, ::chat::TextChatMsgRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_TextChatMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TextChatMsg() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_TextChatMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TextChatMsg(::grpc::ServerContext* /*context*/, const ::chat::TextChatMsgReq* /*request*/, ::chat::TextChatMsgRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTextChatMsg(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_TextChatMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_TextChatMsg() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->TextChatMsg(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_TextChatMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TextChatMsg(::grpc::ServerContext* /*context*/, const ::chat::TextChatMsgReq* /*request*/, ::chat::TextChatMsgRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* TextChatMsg(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* TextChatMsg(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TextChatMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_TextChatMsg() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat::TextChatMsgReq, ::chat::TextChatMsgRsp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat::TextChatMsgReq, ::chat::TextChatMsgRsp>* streamer) {
                       return this->StreamedTextChatMsg(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_TextChatMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TextChatMsg(::grpc::ServerContext* /*context*/, const ::chat::TextChatMsgReq* /*request*/, ::chat::TextChatMsgRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTextChatMsg(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat::TextChatMsgReq,::chat::TextChatMsgRsp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_TextChatMsg<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_TextChatMsg<Service > StreamedService;
};

}  // namespace chat


#endif  // GRPC_chat_5fservice_2eproto__INCLUDED
