// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chat_service.proto

#include "chat_service.pb.h"
#include "chat_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace chat {

static const char* ChatService_method_names[] = {
  "/chat.ChatService/TextChatMsg",
};

std::unique_ptr< ChatService::Stub> ChatService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChatService::Stub> stub(new ChatService::Stub(channel));
  return stub;
}

ChatService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_TextChatMsg_(ChatService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ChatService::Stub::TextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq& request, ::chat::TextChatMsgRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chat::TextChatMsgReq, ::chat::TextChatMsgRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TextChatMsg_, context, request, response);
}

void ChatService::Stub::experimental_async::TextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq* request, ::chat::TextChatMsgRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chat::TextChatMsgReq, ::chat::TextChatMsgRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TextChatMsg_, context, request, response, std::move(f));
}

void ChatService::Stub::experimental_async::TextChatMsg(::grpc::ClientContext* context, const ::chat::TextChatMsgReq* request, ::chat::TextChatMsgRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TextChatMsg_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::TextChatMsgRsp>* ChatService::Stub::PrepareAsyncTextChatMsgRaw(::grpc::ClientContext* context, const ::chat::TextChatMsgReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chat::TextChatMsgRsp, ::chat::TextChatMsgReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TextChatMsg_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chat::TextChatMsgRsp>* ChatService::Stub::AsyncTextChatMsgRaw(::grpc::ClientContext* context, const ::chat::TextChatMsgReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTextChatMsgRaw(context, request, cq);
  result->StartCall();
  return result;
}

ChatService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chat::TextChatMsgReq, ::chat::TextChatMsgRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::TextChatMsgReq* req,
             ::chat::TextChatMsgRsp* resp) {
               return service->TextChatMsg(ctx, req, resp);
             }, this)));
}

ChatService::Service::~Service() {
}

::grpc::Status ChatService::Service::TextChatMsg(::grpc::ServerContext* context, const ::chat::TextChatMsgReq* request, ::chat::TextChatMsgRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace chat

